name: Bug Report
description: File a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees:
  - sebastienfi

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please provide as much information as possible to help us understand and resolve the issue.

  - type: input
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you found...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical - System crash, loss of data, severe memory leak.
        - High - Major functionality is broken, the system is unusable in some scenarios.
        - Medium - Minor functionality is not working as expected.
        - Low - Cosmetic issues, minor inconveniences.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Add any other context or screenshots about the bug report here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, I confirm I've read and acknowledge the [Code of Conduct](../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
