name: Comment on PR with Structurizr Diagrams

on:
    workflow_run:
        types:
            - completed
        workflows:
            - "Update Structurizr Diagrams"

jobs:
    comment-on-pr:
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        permissions:
            contents: read # Allow to work with the contents of the repository, including git pull.
            pull-requests: write # Allow to list and create pr's comments.
        steps:
        - uses: sebastienfi/structurizr-pr-comment@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }} # This token will be used by the action to perform git pull, pr read, pr comment, pr comment edit, pr comment reaction.
            output-path: 'docs/diagrams/' # The output folder for generated images.